"""Send the generated summary to the recipient via SMTP."""

import smtplib
import logging

import markdown as md
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from app.core.config import settings

logger = logging.getLogger(__name__)


def send_email(to_address: str, summary_markdown: str) -> None:
    """Send an HTML email containing the sales summary."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Your AI-Generated Sales Insight Brief"
    msg["From"] = settings.EMAIL_FROM or settings.SMTP_USER
    msg["To"] = to_address

    # Plain-text fallback
    msg.attach(MIMEText(summary_markdown, "plain", "utf-8"))

    # Rich HTML version
    html_body = f"""\
<html>
<head>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e;
         max-width: 700px; margin: auto; padding: 24px; line-height: 1.6; }}
  h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 8px; }}
  h2 {{ color: #0f3460; margin-top: 24px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #0f3460; color: #fff; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .footer {{ margin-top: 32px; font-size: 12px; color: #888;
             border-top: 1px solid #eee; padding-top: 12px; }}
</style>
</head>
<body>
{md.markdown(summary_markdown, extensions=["tables", "fenced_code"])}
<div class="footer">
  <p>Generated by <strong>Sales Insight Automator</strong> &middot; Rabbitt AI</p>
</div>
</body>
</html>"""
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    logger.info("Sending email to %s via %s:%s", to_address, settings.SMTP_HOST, settings.SMTP_PORT)

    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.sendmail(msg["From"], to_address, msg.as_string())

    logger.info("Email sent successfully to %s", to_address)
